<a href="https://colab.research.google.com/github/azarmlengineer/azarmlengineer/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/excel_sheets/titanic.csv")

In [ ]:
data.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data.shape

(891, 12)

In [ ]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
cat = data.dtypes[data.dtypes == 'object'].index

In [ ]:
data[cat].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
sorted(data["Name"])[0:15]

['Abbing, Mr. Anthony',
 'Abbott, Mr. Rossmore Edward',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Abelson, Mr. Samuel',
 'Abelson, Mrs. Samuel (Hannah Wizosky)',
 'Adahl, Mr. Mauritz Nils Martin',
 'Adams, Mr. John',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Aks, Mrs. Sam (Leah Rosen)',
 'Albimona, Mr. Nassef Cassem',
 'Alexander, Mr. William',
 'Alhomaki, Mr. Ilmari Rudolf',
 'Ali, Mr. Ahmed',
 'Ali, Mr. William',
 'Allen, Miss. Elisabeth Walton']

In [ ]:
data["Name"].describe()

count                         891
unique                        891
top       Braund, Mr. Owen Harris
freq                            1
Name: Name, dtype: object

In [ ]:
data["Cabin"].describe()

count         204
unique        147
top       B96 B98
freq            4
Name: Cabin, dtype: object

In [ ]:
survived = pd.Categorical(data["Survived"])

In [ ]:
survived

[0, 1, 1, 1, 0, ..., 0, 1, 0, 1, 0]
Length: 891
Categories (2, int64): [0, 1]

In [ ]:
new_updated = survived.rename_categories(["Alive", "Dead"],inplace=True)

<ipython-input-14-464826e50943>:1: FutureWarning: The `inplace` parameter in pandas.Categorical.rename_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  new_updated = survived.rename_categories(["Alive", "Dead"],inplace=True)


In [ ]:
new_updated

In [ ]:
survived

['Alive', 'Dead', 'Dead', 'Dead', 'Alive', ..., 'Alive', 'Dead', 'Alive', 'Dead', 'Alive']
Length: 891
Categories (2, object): ['Alive', 'Dead']

In [ ]:
data.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
class_list = pd.Categorical(data['Pclass'],ordered=False)

In [ ]:
nclass = class_list.rename_categories(['Class1','class2','class3'])

In [ ]:
nclass

['class3', 'Class1', 'class3', 'Class1', 'class3', ..., 'class2', 'Class1', 'class3', 'Class1', 'class3']
Length: 891
Categories (3, object): ['Class1', 'class2', 'class3']

In [ ]:
char_cabin = data["Cabin"].astype(str)

In [ ]:
char_cabin

0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
886     nan
887     B42
888     nan
889    C148
890     nan
Name: Cabin, Length: 891, dtype: object

In [ ]:
new_cabin = np.array([cabin[0] for cabin in char_cabin])

In [ ]:
new_cabin = pd.Categorical(new_cabin)

In [ ]:
new_cabin

['n', 'C', 'n', 'C', 'n', ..., 'n', 'B', 'n', 'C', 'n']
Length: 891
Categories (9, object): ['A', 'B', 'C', 'D', ..., 'F', 'G', 'T', 'n']

In [ ]:
data["Age"].head(5)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [ ]:
missing=np.where(data['Age'].isnull()==True)

In [ ]:
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888]),)

In [ ]:
len(missing[0])

177

In [ ]:
index = np.where(data["Fare"] == max(data["Fare"]))

In [ ]:
index

(array([258, 679, 737]),)

In [ ]:
data.iloc[index]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [ ]:
index

(array([258, 679, 737]),)

In [ ]:
data[["Fare","Ticket"]]

Fare            Ticket
0     7.2500         A/5 21171
1    71.2833          PC 17599
2     7.9250  STON/O2. 3101282
3    53.1000            113803
4     8.0500            373450
..       ...               ...
886  13.0000            211536
887  30.0000            112053
888  23.4500        W./C. 6607
889  30.0000            111369
890   7.7500            370376

[891 rows x 2 columns]

In [ ]:
data.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data["Family"] = data["SibSp"]+data["Parch"]
most_family = np.where(data["Family"] == max(data["Family"]))
data.iloc[most_family]

PassengerId  Survived  Pclass                               Name     Sex  \
159          160         0       3         Sage, Master. Thomas Henry    male   
180          181         0       3       Sage, Miss. Constance Gladys  female   
201          202         0       3                Sage, Mr. Frederick    male   
324          325         0       3           Sage, Mr. George John Jr    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
159  NaN      8      2  CA. 2343  69.55   NaN        S      10  
180  NaN      8      2  CA. 2343  69.55   NaN        S      10  
201  NaN      8      2  CA. 2343  69.55   NaN        S      10  
324  NaN      8      2  CA. 2343  69.55   NaN        S      10  
792  NaN      8      2  CA. 2343  69.55   NaN        S      10  
846  NaN      8      2  CA. 2343  69.55   NaN        S      10  
863  NaN      8      2  CA. 2343  69.55   NaN        S      10

In [ ]:
from numpy.random import randn as rn
np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
columns = ['w','x','y','z']
df = pd.DataFrame(data=matrix_data, columns=columns,index=row_labels)
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['x']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: x, dtype: float64

In [ ]:
df['x','z']

KeyError: ignored

In [ ]:
df[['x','z']]

x         z
A  0.628133  0.503826
B -0.319318  0.605965
C  0.740122 -0.589001
D -0.758872  0.955057
E  1.978757  0.683509

In [ ]:
df.x

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: x, dtype: float64

In [ ]:
df['new'] = df['x']+df['z']
df

w         x         y         z       new
A  2.706850  0.628133  0.907969  0.503826  1.131958
B  0.651118 -0.319318 -0.848077  0.605965  0.286647
C -2.018168  0.740122  0.528813 -0.589001  0.151122
D  0.188695 -0.758872 -0.933237  0.955057  0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266

In [ ]:
df.drop('new')

KeyError: ignored

In [ ]:
df.drop('new',axis=1)
df

w         x         y         z       new
A  2.706850  0.628133  0.907969  0.503826  1.131958
B  0.651118 -0.319318 -0.848077  0.605965  0.286647
C -2.018168  0.740122  0.528813 -0.589001  0.151122
D  0.188695 -0.758872 -0.933237  0.955057  0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266

In [ ]:
df.drop('new',axis=1,inplace=True)
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.iloc[2]

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: C, dtype: float64

In [ ]:
df.iloc['B']

TypeError: ignored

In [ ]:
df.loc['B']

w    0.651118
x   -0.319318
y   -0.848077
z    0.605965
Name: B, dtype: float64