<a href="https://colab.research.google.com/github/azarmlengineer/azarmlengineer/blob/main/python/numpy_1.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [2]:
type(np.array([1,2,3]))


numpy.ndarray

In [3]:
#upcasting
np.array([1,2,3.0,4.0])

array([1., 2., 3., 4.])

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#dimension
from numpy.core.fromnumeric import ndim
np.array([1,2,3,4,5,6],ndmin=8)

array([[[[[[[[1, 2, 3, 4, 5, 6]]]]]]]])

In [10]:
arr = np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i4')])

In [12]:
arr['a']
arr['b']

array([2, 4], dtype=int32)

In [13]:
arr['a']

array([1, 3], dtype=int32)

In [15]:
arr = np.array(np.mat('1 2 ; 3,4'),subok=True)

In [16]:
arr

matrix([[1, 2],
        [3, 4]])

### np.copy

In [1]:
x = [1,2,3]

In [2]:
y=x

In [3]:
x

[1, 2, 3]

In [4]:
y

[1, 2, 3]

In [7]:
z = np.copy(x)

In [8]:
z

array([1, 2, 3])

In [9]:
x[0]=10

In [10]:
x

[10, 2, 3]

In [11]:
y # changes in x will change value of y also called shallow copy

[10, 2, 3]

In [12]:
z # changes in x will not change z this is called deepcopy

array([1, 2, 3])

np.fromfunction ( Lambda)

In [14]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [24]:
iter = (x*x for x in range(5))

In [25]:
iter

<generator object <genexpr> at 0x7db009c7c4a0>

In [21]:
np.fromiter(iter,int)

array([ 0,  1,  4,  9, 16])

In [22]:
iter = [x*x for x in range(5)]

In [23]:
iter #list

[0, 1, 4, 9, 16]

In [26]:
np.fromiter(iter,float)

array([ 0.,  1.,  4.,  9., 16.])

String IO

In [27]:
from io import StringIO

In [34]:
c = StringIO("1 2\n 3 4")

In [29]:
c

In [35]:
np.loadtxt(c)

array([[1., 2.],
       [3., 4.]])

In [46]:
d = StringIO("M 27 83 \n F 25 65")

In [47]:
np.loadtxt(d, dtype={'names':('gender','age','weight'),'formats':('S1','i4','i4')})

array([(b'M', 27, 83), (b'F', 25, 65)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<i4')])