<a href="https://colab.research.google.com/github/azarmlengineer/azarmlengineer/blob/main/python/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUmpy Array

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(5)

array([0.29357245, 0.44079597, 0.14581972, 0.8886485 , 0.19717361])

In [ ]:
np.random.randn(2)

array([-0.67739224, -0.46067566])

In [ ]:
np.random.randint(0,5)

2

In [ ]:
np.random.randint(0,100)

88

In [ ]:
np.random.randint(0,100,10)

array([68, 90,  3, 93, 83, 90, 93,  7, 60,  8])

In [ ]:
arr = np.arange(0,25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
ranarr

array([ 1, 19, 29, 39, 46, 38, 15, 37, 21, 43])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

24

In [ ]:
arr.min()

0

In [ ]:
arr.argmax()

24

In [ ]:
arr.argmin()

0

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
n = arr.reshape(5,5)

In [ ]:
n.shape

(5, 5)

Numpy indexing and selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5:7]=100 #broadcasting

In [ ]:
arr

array([  0,   1,   2,   3,   4, 100, 100,   7,   8,   9,  10])

In [ ]:
arr_copy = arr.copy()
arr_copy[5:]=100
# if we use copy method the changes wont effect original

In [ ]:
arr_copy

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([  0,   1,   2,   3,   4, 100, 100,   7,   8,   9,  10])

2-D array indexing


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[0][1]

2

In [ ]:
arr[0][0]

1

In [ ]:
arr[2][1]

8

In [ ]:
arr[0,1]

2

In [ ]:
arr[0,0]

1

In [ ]:
arr[2,1]

8

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

selection

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr[arr>5]

array([6, 7, 8, 9])

In [ ]:
arr[arr<9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9])

Exercise

In [ ]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[0][7]

7

In [ ]:
arr[1][7]

17

In [ ]:
arr[2][7]

27

In [ ]:
arr[3][7]

37

In [ ]:
arr[4][7]

47

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[2:4,7:9]

array([[27, 28],
       [37, 38]])

In [ ]:
arr[2:3,5:6]

array([[25]])

In [ ]:
arr[3,4]


34

In [ ]:
arr[1:2,3:4]

array([[13]])

In [ ]:
arr[1,3]

13

In [ ]:
arr = [1,2,3]
arr

[1, 2, 3]

In [ ]:
for x in arr:
  print(x)

1
2
3


In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[3:,8:]

array([[38, 39],
       [48, 49]])

Numpy **Operations**

Array with array

Array with scalars

universal array functions

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr/arr

<ipython-input-17-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
1/arr

<ipython-input-20-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])